/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintIdRouteImport } from './routes/print.$id'
import { Route as PrintCashCheckoutIdRouteImport } from './routes/print-cash-checkout.$id'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintIdRoute = PrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCashCheckoutIdRoute = PrintCashCheckoutIdRouteImport.update({
  id: '/print-cash-checkout/$id',
  path: '/print-cash-checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
  '/transactions': typeof TransactionsRoute
  '/print-cash-checkout/$id': typeof PrintCashCheckoutIdRoute
  '/print/$id': typeof PrintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
  '/transactions': typeof TransactionsRoute
  '/print-cash-checkout/$id': typeof PrintCashCheckoutIdRoute
  '/print/$id': typeof PrintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
  '/transactions': typeof TransactionsRoute
  '/print-cash-checkout/$id': typeof PrintCashCheckoutIdRoute
  '/print/$id': typeof PrintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/login'
    | '/sales'
    | '/transactions'
    | '/print-cash-checkout/$id'
    | '/print/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/login'
    | '/sales'
    | '/transactions'
    | '/print-cash-checkout/$id'
    | '/print/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/login'
    | '/sales'
    | '/transactions'
    | '/print-cash-checkout/$id'
    | '/print/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  SalesRoute: typeof SalesRoute
  TransactionsRoute: typeof TransactionsRoute
  PrintCashCheckoutIdRoute: typeof PrintCashCheckoutIdRoute
  PrintIdRoute: typeof PrintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$id': {
      id: '/print/$id'
      path: '/print/$id'
      fullPath: '/print/$id'
      preLoaderRoute: typeof PrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-cash-checkout/$id': {
      id: '/print-cash-checkout/$id'
      path: '/print-cash-checkout/$id'
      fullPath: '/print-cash-checkout/$id'
      preLoaderRoute: typeof PrintCashCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  SalesRoute: SalesRoute,
  TransactionsRoute: TransactionsRoute,
  PrintCashCheckoutIdRoute: PrintCashCheckoutIdRoute,
  PrintIdRoute: PrintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
